name: Sync Submodule

on:
  schedule:
    # Run every day at 2 AM UTC (adjust timezone as needed)
    - cron: '0 2 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  sync-submodule:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        submodules: true
        
    - name: Update submodule
      run: |
        git submodule update --remote --merge
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        
    - name: Check for changes
      id: check-changes
      run: |
        if git diff --quiet; then
          echo "has-changes=false" >> $GITHUB_OUTPUT
        else
          echo "has-changes=true" >> $GITHUB_OUTPUT
        fi
        
    - name: Commit and push changes
      if: steps.check-changes.outputs.has-changes == 'true'
      run: |
        git add data/ccf-deadlines
        git commit -m "chore: update ccf-deadlines submodule"
        git push
